/* The groups the gallery shows, in the order the kit is built. The part names are what the index
   exports, so scripts/parity.mjs and this list describe the same thing from two ends. */

export type Group = { id: string; title: string; note: string; parts: string[] };

export const GROUPS: Group[] = [
  {
    id: 'text',
    title: 'Text',
    note: 'The ladder, and the words that qualify a figure.',
    parts: ['Text', 'Status', 'Count', 'Lede', 'Figure', 'FigureSwatch'],
  },
  {
    id: 'layout',
    title: 'Layout',
    note: 'How things sit next to each other, and the surfaces they sit on.',
    parts: [
      'Stack',
      'Cluster',
      'Row',
      'Divider',
      'Head',
      'Section',
      'Panel',
      'PanelHead',
      'PanelBody',
      'PanelFoot',
      'Collection',
      'Item',
      'ItemText',
      'Meta',
      'Fact',
      'Empty',
      'Waiting',
      'Failed',
    ],
  },
  {
    id: 'controls',
    title: 'Controls',
    note: 'What a finger presses. Every one crosses to its pressed ground over the motion tokens.',
    parts: [
      'Button',
      'LinkButton',
      'Tray',
      'Tabs',
      'Avatar',
      'AvatarStack',
      'Crumbs',
      'Pages',
      'Progress',
      'Skeleton',
      'Spinner',
      'Delta',
    ],
  },
  {
    id: 'form',
    title: 'Form',
    note: 'Fields, and the keyboard each one asks the OS for.',
    parts: [
      'Form',
      'Fieldset',
      'Field',
      'Input',
      'Textarea',
      'Group',
      'Choice',
      'Switch',
      'Select',
      'Toolbar',
      'FormActions',
    ],
  },
  {
    id: 'blocks',
    title: 'Blocks',
    note: 'What a page is built out of.',
    parts: [
      'Hero',
      'Tiles',
      'Tile',
      'Stats',
      'Stat',
      'Cta',
      'Callout',
      'Sheet',
      'SheetRow',
      'Facts',
      'FactGroup',
      'NamedFact',
      'ProseTitle',
    ],
  },
  {
    id: 'table',
    title: 'Table',
    note: 'The one place a rule between repeating rows belongs.',
    parts: ['TableWrap', 'Table', 'RowTitle', 'TableFoot'],
  },
  {
    id: 'listing',
    title: 'Listing',
    note: 'Flush rows in one box, told apart by a rule. A collection is told apart by room.',
    parts: ['Listing', 'ListingHead', 'ListingGroup', 'ListingRow'],
  },
  {
    id: 'data',
    title: 'Data',
    note: 'Readings. Nothing here takes a colour of its own.',
    parts: [
      'Log',
      'LogDay',
      'LogLine',
      'Diff',
      'DiffFile',
      'DiffRow',
      'Source',
      'Scale',
      'Calendar',
      'Sparkline',
      'Columns',
    ],
  },
  {
    id: 'feedback',
    title: 'Feedback',
    note: 'What interrupts, and what folds away.',
    parts: ['Dialog', 'Drawer', 'Menu', 'ToastProvider', 'useToast', 'Disclosure', 'Accordion'],
  },
  {
    id: 'chrome',
    title: 'Chrome',
    note: 'The bar, the seal, the footer, and the icon set.',
    parts: ['Bar', 'Seal', 'Footer', 'Icons'],
  },
  {
    id: 'markdown',
    title: 'Markdown',
    note: 'What an issue body actually uses, drawn as native views.',
    parts: ['Markdown'],
  },
];
