/* Ports Kasane's icon set to react-native-svg.

     node tokens/icons.mjs ../kurobeni

   Written by transforming Kasane's own generated file, not by redrawing: the set, the geometry and
   the stroke are whatever Kasane says they are, and a new icon there arrives here by rerunning
   this. Output: tokens/icons.tsx, copied into expo/. */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const kasane = resolve(process.argv[2] ?? join(here, '..', '..', 'kurobeni'));
const src = readFileSync(join(kasane, 'src', 'react', 'icons.generated.tsx'), 'utf8');

/* every icon: its name, the lucide comment above it, and the shapes inside its svg */
const icons = [];
for (const m of src.matchAll(
  /\/\*\* (lucide [^*]+) \*\/\s*export function (Icon\w+)\(\{[^}]*\}: IconProps\) \{[\s\S]*?<svg[^>]*>([\s\S]*?)<\/svg>/g,
)) {
  const [, note, name, body] = m;
  const shapes = [];
  for (const tag of body.matchAll(/<(circle|path|rect|line|polyline|polygon)\s+([^/>]*)\/>/g)) {
    const [, kind, attrs] = tag;
    const props = {};
    for (const a of attrs.matchAll(/([\w-]+)="([^"]*)"/g)) props[a[1]] = a[2];
    shapes.push({ kind, props });
  }
  if (!shapes.length) throw new Error(`${name} has no shapes`);
  icons.push({ name, note, shapes });
}
if (icons.length < 17) throw new Error(`only found ${icons.length} icons`);

/* react-native-svg names a few attributes differently, and takes numbers where the web takes
   strings. Anything not in here is passed through as it was authored. */
const RENAME = { 'stroke-width': 'strokeWidth', 'stroke-linecap': 'strokeLinecap' };
const NUMERIC = new Set(['cx', 'cy', 'r', 'x', 'y', 'width', 'height', 'rx', 'ry', 'x1', 'x2', 'y1', 'y2']);

const attrs = (props) =>
  Object.entries(props)
    .map(([k, v]) => {
      const key = RENAME[k] ?? k;
      return NUMERIC.has(key) ? `${key}={${v}}` : `${key}="${v}"`;
    })
    .join(' ');

const KIND = {
  circle: 'Circle',
  path: 'Path',
  rect: 'Rect',
  line: 'Line',
  polyline: 'Polyline',
  polygon: 'Polygon',
};

const used = [...new Set(icons.flatMap((i) => i.shapes.map((s) => KIND[s.kind])))].sort();

const out = `// Generated by tokens/icons.mjs from Kasane's icons.generated.tsx (lucide, ISC). Do not edit.

import Svg, { ${used.join(', ')} } from 'react-native-svg';
import { useTheme } from './kasane/theme';

/* The same ${icons.length} icons the web has, drawn from the same geometry. The stroke takes the ink of
   whatever it sits in, so an icon inside a filled control reads on the fill. */

export type IconProps = { size?: number; colour?: string };

function useInk(colour?: string) {
  const { t } = useTheme();
  return colour ?? t.fg.default;
}

${icons
  .map(
    ({ name, note, shapes }) => `/** ${note} */
export function ${name}({ size = 18, colour }: IconProps) {
  const ink = useInk(colour);
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
${shapes
      .map(
        (s) =>
          `      <${KIND[s.kind]} ${attrs(s.props)} stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />`,
      )
      .join('\n')}
    </Svg>
  );
}`,
  )
  .join('\n\n')}
`;

writeFileSync(join(here, 'icons.tsx'), out, 'utf8');
console.log(`wrote tokens/icons.tsx: ${icons.length} icons, ${used.join(', ')}`);
