// Generated by tokens/generate.mjs from Kasane's DTCG source. Do not edit.

import Foundation

public enum Kasane {
  /// Control heights. The same three as the web.
  public enum Control {
    public static let sm: Double = 32
    public static let md: Double = 40
    public static let lg: Double = 48
  }

  /// The one radius. A control at any of the three heights becomes a pill.
  public static let radius: Double = 24

  /// A shadow, in the parts a platform takes. The web writes these as one box-shadow string.
  public struct Shadow: Sendable {
    public let x: Double
    public let y: Double
    public let blur: Double
    public let colour: String
    public let opacity: Double
  }

  public enum Shadows {
    public static let raised = Shadow(x: 0, y: 16, blur: 48, colour: "#221a1e", opacity: 0.18)
    public static let bar = Shadow(x: 0, y: 8, blur: 32, colour: "#221a1e", opacity: 0.16)
  }

  /// The space ladder, in points, remapped the way data-kb-density=compact remaps it. A phone is
  /// always the compact case.
  public enum Space {
    public static let s4: Double = 4
    public static let s8: Double = 8
    public static let s12: Double = 12
    public static let s16: Double = 12
    public static let s24: Double = 16
    public static let s32: Double = 24
    public static let s40: Double = 40
    public static let s48: Double = 32
    public static let s64: Double = 48
    public static let s96: Double = 64
    public static let s128: Double = 128
    public static let s160: Double = 160
  }

  /// The ladder as the web writes it, for anything that has to match a desktop measurement.
  public enum Room {
    public static let s4: Double = 4
    public static let s8: Double = 8
    public static let s12: Double = 12
    public static let s16: Double = 16
    public static let s24: Double = 24
    public static let s32: Double = 32
    public static let s40: Double = 40
    public static let s48: Double = 48
    public static let s64: Double = 64
    public static let s96: Double = 96
    public static let s128: Double = 128
    public static let s160: Double = 160
  }

  /// Type sizes before the user's text scale is applied. Not named Type: Swift reserves that
  /// as a member name, since it collides with the foo.Type expression.
  public struct TypeStep: Sendable {
    public let size: Double
    public let leading: Double
    public let tracking: Double
  }

  public enum TypeScale {
    public static let t12 = TypeStep(size: 12, leading: 1.5, tracking: 0)
    public static let t14 = TypeStep(size: 14, leading: 1.5, tracking: 0)
    public static let t16 = TypeStep(size: 16, leading: 1.55, tracking: 0)
    public static let t18 = TypeStep(size: 18, leading: 1.5, tracking: 0)
    public static let t20 = TypeStep(size: 20, leading: 1.4, tracking: 0)
    public static let t24 = TypeStep(size: 24, leading: 1.25, tracking: -0.01)
    public static let t32 = TypeStep(size: 32, leading: 1.15, tracking: -0.015)
    public static let t40 = TypeStep(size: 40, leading: 1.1, tracking: -0.02)
    public static let t72 = TypeStep(size: 72, leading: 1, tracking: -0.025)
  }

  /// Colours by dotted name, per theme. Hex as authored.
  public static let light: [String: String] = [
    "fg.default": "#221a1e",
    "fg.secondary": "#5a5156",
    "fg.muted": "#68606a",
    "fg.onAccent": "#ffffff",
    "fg.onFill": "#f3ede4",
    "fg.toast": "#221a1e",
    "fg.toastOk": "#25664a",
    "fg.toastErr": "#b3262d",
    "bg.page": "#f3ede4",
    "bg.surface": "#fbf8f3",
    "bg.raised": "#e7dfd3",
    "bg.pressed": "#d9cfc0",
    "bg.tile": "#ffffff",
    "bg.toast": "#fbf8f3",
    "bg.scrim": "rgba(19, 13, 16, 0.6)",
    "bg.dim": "rgba(127, 127, 127, 0.35)",
    "bg.dimPressed": "rgba(127, 127, 127, 0.55)",
    "border.control": "#7d7378",
    "border.strong": "#221a1e",
    "border.hairline": "#d5cdc2",
    "border.toast": "#7d7378",
    "accent.default": "#b3262d",
    "accent.hover": "#951f26",
    "accent.active": "#7a191e",
    "fill.default": "#2b1b21",
    "fill.hover": "#412b34",
    "fill.active": "#54404a",
    "status.ok": "#25664a",
    "status.warn": "#805307",
    "status.err": "#b3262d",
    "series.1": "#a77836",
    "series.2": "#008ea7",
    "series.3": "#003923",
    "series.4": "#501756",
    "series.5": "#943867",
    "series.6": "#34579f",
    "series.7": "#6c8961",
    "series.8": "#474400",
    "focus.color": "#b3262d",
  ]

  public static let dark: [String: String] = [
    "fg.default": "#f1eae2",
    "fg.secondary": "#b8adb0",
    "fg.muted": "#9c9195",
    "fg.onAccent": "#130d10",
    "fg.onFill": "#130d10",
    "fg.toast": "#130d10",
    "fg.toastOk": "#25664a",
    "fg.toastErr": "#b3262d",
    "bg.page": "#130d10",
    "bg.surface": "#1e161a",
    "bg.raised": "#2c2228",
    "bg.pressed": "#3a2e35",
    "bg.tile": "#362a33",
    "bg.toast": "#f1eae2",
    "bg.scrim": "rgba(19, 13, 16, 0.6)",
    "bg.dim": "rgba(127, 127, 127, 0.35)",
    "bg.dimPressed": "rgba(127, 127, 127, 0.55)",
    "border.control": "#7f7378",
    "border.strong": "#f1eae2",
    "border.hairline": "#3a2f35",
    "border.toast": "#f1eae2",
    "accent.default": "#e8646c",
    "accent.hover": "#f07e85",
    "accent.active": "#dc525a",
    "fill.default": "#f1eae2",
    "fill.hover": "#d9d0c6",
    "fill.active": "#c1b6aa",
    "status.ok": "#86c9a4",
    "status.warn": "#e2b75f",
    "status.err": "#e8646c",
    "series.1": "#ad844e",
    "series.2": "#15aecc",
    "series.3": "#2f7556",
    "series.4": "#954c9a",
    "series.5": "#c5578e",
    "series.6": "#6583cf",
    "series.7": "#89a77d",
    "series.8": "#867c0c",
    "focus.color": "#e8646c",
  ]
}
