/* Ports the kurobeni.jp seal to react-native-svg.

     node tokens/seal.mjs ../gitea-next

   The outlines are read out of the web component, not redrawn. The press filter is dropped: it is
   an feTurbulence and an feDisplacementMap, which react-native-svg does not carry on both
   platforms, and it only roughens the frame. Written in tokens/deviations.json.

   Output: tokens/seal.tsx, copied into expo/. */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const site = resolve(process.argv[2] ?? join(here, '..', '..', 'gitea-next'));
const src = readFileSync(join(site, 'components', 'seal.tsx'), 'utf8');

const ellipse = /<ellipse\s+([^/>]*)\/>/.exec(src);
if (!ellipse) throw new Error('no ellipse in the seal');
const at = (attrs, name) => new RegExp(`${name}="([^"]*)"`).exec(attrs)?.[1];

const frame = {
  cx: at(ellipse[1], 'cx'),
  cy: at(ellipse[1], 'cy'),
  rx: at(ellipse[1], 'rx'),
  ry: at(ellipse[1], 'ry'),
  width: at(ellipse[1], 'strokeWidth'),
};

const glyphs = [...src.matchAll(/<path\s+d="([^"]+)"\s+transform="([^"]+)"/g)].map((m) => ({
  d: m[1],
  transform: m[2],
}));
if (glyphs.length !== 2) throw new Error(`expected 2 glyphs, found ${glyphs.length}`);

const out = `// Generated by tokens/seal.mjs from the web component. Do not edit.

import Svg, { Ellipse, G, Path } from 'react-native-svg';
import { useTheme } from './kasane/theme';

/* The seal: 黑紅 in small seal script, an oval 朱文 impression. Outlines from Chong Xi Small Seal
   (崇羲篆體, Academia Sinica, CC BY-ND 3.0 TW), as drawn. This is the kurobeni.jp mark, not part of
   Kasane.

   The web roughens the frame with an feTurbulence. That filter does not carry to both platforms, so
   here the frame is drawn clean. */

export function Seal({
  size = ${'${'}40},
  label = 'Kurobeni',
  decorative,
  colour,
}: {
  size?: number;
  label?: string;
  /** hidden from the tree, for a seal inside a named link */
  decorative?: boolean;
  colour?: string;
}) {
  const { t } = useTheme();
  const ink = colour ?? t.accent.default;
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 100 100"
      accessibilityRole={decorative ? undefined : 'image'}
      accessibilityLabel={decorative ? undefined : label}
    >
      <Ellipse
        cx={${frame.cx}}
        cy={${frame.cy}}
        rx={${frame.rx}}
        ry={${frame.ry}}
        fill="none"
        stroke={ink}
        strokeWidth={${frame.width}}
      />
      <G fill={ink} stroke={ink} strokeWidth={12} strokeLinejoin="round">
${glyphs
  .map((g) => `        <Path d="${g.d}" transform="${g.transform}" />`)
  .join('\n')}
      </G>
    </Svg>
  );
}
`.replace('${40}', '40');

writeFileSync(join(here, 'seal.tsx'), out, 'utf8');
console.log(`wrote tokens/seal.tsx: the frame and ${glyphs.length} glyphs`);
