// Generated by tokens/icons.mjs from Kasane's icons.generated.tsx (lucide, ISC). Do not edit.

import Svg, { Circle, Line, Path } from 'react-native-svg';
import { useTheme } from './kasane/theme';

/* The same 17 icons the web has, drawn from the same geometry. The stroke takes the ink of
   whatever it sits in, so an icon inside a filled control reads on the fill. */

export type IconProps = { size?: number; colour?: string };

function useInk(colour?: string) {
  const { t } = useTheme();
  return colour ?? t.fg.default;
}

/** lucide Sun */
export function IconSun({ size = 18, colour }: IconProps) {
  const ink = useInk(colour);
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <Circle cx={12} cy={12} r={4} stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
      <Path d="M12 2v2" stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
      <Path d="M12 20v2" stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
      <Path d="m4.93 4.93 1.41 1.41" stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
      <Path d="m17.66 17.66 1.41 1.41" stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
      <Path d="M2 12h2" stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
      <Path d="M20 12h2" stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
      <Path d="m6.34 17.66-1.41 1.41" stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
      <Path d="m19.07 4.93-1.41 1.41" stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
    </Svg>
  );
}

/** lucide Moon */
export function IconMoon({ size = 18, colour }: IconProps) {
  const ink = useInk(colour);
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <Path d="M20.985 12.486a9 9 0 1 1-9.473-9.472c.405-.022.617.46.402.803a6 6 0 0 0 8.268 8.268c.344-.215.825-.004.803.401" stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
    </Svg>
  );
}

/** lucide X */
export function IconClose({ size = 18, colour }: IconProps) {
  const ink = useInk(colour);
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <Path d="M18 6 6 18" stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
      <Path d="m6 6 12 12" stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
    </Svg>
  );
}

/** lucide ArrowUp */
export function IconArrowUp({ size = 18, colour }: IconProps) {
  const ink = useInk(colour);
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <Path d="m5 12 7-7 7 7" stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
      <Path d="M12 19V5" stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
    </Svg>
  );
}

/** lucide ArrowDown */
export function IconArrowDown({ size = 18, colour }: IconProps) {
  const ink = useInk(colour);
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <Path d="M12 5v14" stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
      <Path d="m19 12-7 7-7-7" stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
    </Svg>
  );
}

/** lucide Search */
export function IconSearch({ size = 18, colour }: IconProps) {
  const ink = useInk(colour);
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <Path d="m21 21-4.34-4.34" stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
      <Circle cx={11} cy={11} r={8} stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
    </Svg>
  );
}

/** lucide ChevronDown */
export function IconChevronDown({ size = 18, colour }: IconProps) {
  const ink = useInk(colour);
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <Path d="m6 9 6 6 6-6" stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
    </Svg>
  );
}

/** lucide Check */
export function IconCheck({ size = 18, colour }: IconProps) {
  const ink = useInk(colour);
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <Path d="M20 6 9 17l-5-5" stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
    </Svg>
  );
}

/** lucide Ellipsis */
export function IconMore({ size = 18, colour }: IconProps) {
  const ink = useInk(colour);
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <Circle cx={12} cy={12} r={1} stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
      <Circle cx={19} cy={12} r={1} stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
      <Circle cx={5} cy={12} r={1} stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
    </Svg>
  );
}

/** lucide Menu */
export function IconMenu({ size = 18, colour }: IconProps) {
  const ink = useInk(colour);
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <Path d="M4 5h16" stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
      <Path d="M4 12h16" stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
      <Path d="M4 19h16" stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
    </Svg>
  );
}

/** lucide File */
export function IconFile({ size = 18, colour }: IconProps) {
  const ink = useInk(colour);
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <Path d="M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z" stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
      <Path d="M14 2v5a1 1 0 0 0 1 1h5" stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
    </Svg>
  );
}

/** lucide Folder */
export function IconFolder({ size = 18, colour }: IconProps) {
  const ink = useInk(colour);
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <Path d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z" stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
    </Svg>
  );
}

/** lucide GitBranch */
export function IconBranch({ size = 18, colour }: IconProps) {
  const ink = useInk(colour);
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <Path d="M15 6a9 9 0 0 0-9 9V3" stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
      <Circle cx={18} cy={6} r={3} stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
      <Circle cx={6} cy={18} r={3} stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
    </Svg>
  );
}

/** lucide GitCommitHorizontal */
export function IconCommit({ size = 18, colour }: IconProps) {
  const ink = useInk(colour);
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <Circle cx={12} cy={12} r={3} stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
      <Line x1={3} x2={9} y1={12} y2={12} stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
      <Line x1={15} x2={21} y1={12} y2={12} stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
    </Svg>
  );
}

/** lucide CircleDot */
export function IconIssue({ size = 18, colour }: IconProps) {
  const ink = useInk(colour);
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <Circle cx={12} cy={12} r={1} stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
      <Circle cx={12} cy={12} r={10} stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
    </Svg>
  );
}

/** lucide GitPullRequest */
export function IconPullRequest({ size = 18, colour }: IconProps) {
  const ink = useInk(colour);
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <Circle cx={18} cy={18} r={3} stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
      <Circle cx={6} cy={6} r={3} stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
      <Path d="M13 6h3a2 2 0 0 1 2 2v7" stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
      <Line x1={6} x2={6} y1={9} y2={21} stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
    </Svg>
  );
}

/** lucide Tag */
export function IconTag({ size = 18, colour }: IconProps) {
  const ink = useInk(colour);
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <Path d="M12.586 2.586A2 2 0 0 0 11.172 2H4a2 2 0 0 0-2 2v7.172a2 2 0 0 0 .586 1.414l8.704 8.704a2.426 2.426 0 0 0 3.42 0l6.58-6.58a2.426 2.426 0 0 0 0-3.42z" stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
      <Circle cx={7.5} cy={7.5} r={.5} fill="currentColor" stroke={ink} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
    </Svg>
  );
}
