// Generated by tokens/generate.mjs from Kasane's DTCG source. Do not edit.

/** Control heights. Taller than the web: Android asks for 48dp as a minimum. */
export const control = { sm: 44, md: 48, lg: 56 } as const;

/** The one radius. */
export const radius = 24;

/** Shadows in the parts React Native takes. The web writes these as one box-shadow string. */
export const shadow = {
  "raised": {
    "x": 0,
    "y": 16,
    "blur": 48,
    "colour": "#221a1e",
    "opacity": 0.18
  },
  "bar": {
    "x": 0,
    "y": 8,
    "blur": 32,
    "colour": "#221a1e",
    "opacity": 0.16
  }
} as const;

export const space = {
  4: 4,
  8: 8,
  12: 12,
  16: 16,
  24: 24,
  32: 32,
  40: 40,
  48: 48,
  64: 64,
  96: 96,
  128: 128,
  160: 160
} as const;

/** Sizes before the OS text scale is applied. Multiply by PixelRatio.getFontScale(). */
export const type = {
  "12": {
    "size": 12,
    "leading": 1.5,
    "tracking": 0
  },
  "14": {
    "size": 14,
    "leading": 1.5,
    "tracking": 0
  },
  "16": {
    "size": 16,
    "leading": 1.55,
    "tracking": 0
  },
  "18": {
    "size": 18,
    "leading": 1.5,
    "tracking": 0
  },
  "20": {
    "size": 20,
    "leading": 1.4,
    "tracking": 0
  },
  "24": {
    "size": 24,
    "leading": 1.25,
    "tracking": -0.01
  },
  "32": {
    "size": 32,
    "leading": 1.15,
    "tracking": -0.015
  },
  "40": {
    "size": 40,
    "leading": 1.1,
    "tracking": -0.02
  },
  "72": {
    "size": 72,
    "leading": 1,
    "tracking": -0.025
  }
} as const;

export const light = {
  fg: {
    "default": '#221a1e',
    "secondary": '#5a5156',
    "muted": '#68606a',
    "onAccent": '#ffffff',
    "onFill": '#f3ede4',
    "toast": '#221a1e',
    "toastOk": '#25664a',
    "toastErr": '#b3262d',
  },
  bg: {
    "page": '#f3ede4',
    "surface": '#fbf8f3',
    "raised": '#e7dfd3',
    "pressed": '#d9cfc0',
    "tile": '#ffffff',
    "toast": '#fbf8f3',
    "scrim": 'rgba(19, 13, 16, 0.6)',
    "dim": 'rgba(127, 127, 127, 0.35)',
    "dimPressed": 'rgba(127, 127, 127, 0.55)',
  },
  border: {
    "control": '#7d7378',
    "strong": '#221a1e',
    "hairline": '#d5cdc2',
    "toast": '#7d7378',
  },
  accent: {
    "default": '#b3262d',
    "hover": '#951f26',
    "active": '#7a191e',
  },
  fill: {
    "default": '#2b1b21',
    "hover": '#412b34',
    "active": '#54404a',
  },
  status: {
    "ok": '#25664a',
    "warn": '#805307',
    "err": '#b3262d',
  },
  series: {
    "1": '#a77836',
    "2": '#008ea7',
    "3": '#003923',
    "4": '#501756',
    "5": '#943867',
    "6": '#34579f',
    "7": '#6c8961',
    "8": '#474400',
  },
  focus: {
    "color": '#b3262d',
  },
} as const;

export const dark = {
  fg: {
    "default": '#f1eae2',
    "secondary": '#b8adb0',
    "muted": '#9c9195',
    "onAccent": '#130d10',
    "onFill": '#130d10',
    "toast": '#130d10',
    "toastOk": '#25664a',
    "toastErr": '#b3262d',
  },
  bg: {
    "page": '#130d10',
    "surface": '#1e161a',
    "raised": '#2c2228',
    "pressed": '#3a2e35',
    "tile": '#362a33',
    "toast": '#f1eae2',
    "scrim": 'rgba(19, 13, 16, 0.6)',
    "dim": 'rgba(127, 127, 127, 0.35)',
    "dimPressed": 'rgba(127, 127, 127, 0.55)',
  },
  border: {
    "control": '#7f7378',
    "strong": '#f1eae2',
    "hairline": '#3a2f35',
    "toast": '#f1eae2',
  },
  accent: {
    "default": '#e8646c',
    "hover": '#f07e85',
    "active": '#dc525a',
  },
  fill: {
    "default": '#f1eae2',
    "hover": '#d9d0c6',
    "active": '#c1b6aa',
  },
  status: {
    "ok": '#86c9a4',
    "warn": '#e2b75f',
    "err": '#e8646c',
  },
  series: {
    "1": '#ad844e',
    "2": '#15aecc',
    "3": '#2f7556',
    "4": '#954c9a',
    "5": '#c5578e',
    "6": '#6583cf',
    "7": '#89a77d',
    "8": '#867c0c',
  },
  focus: {
    "color": '#e8646c',
  },
} as const;

export type Theme = typeof light;
